-- 1.  RAW_CUSTOMER_FEEDBACK
-- 2.  RAW_INCIDENT_TREND_SUMMARY
-- 3.  RAW_ML_FEATURES
-- 4.  RAW_NETWORK_CONTEXT_STATIC
-- 5.  RAW_ONT_STATUS
-- 6.  RAW_TICKET_SUMMARY
-- 7.  RAW_EVENT_TRANSCRIPTS
-- 8.  RAW_CITY
-- 9.  RAW_CLUSTER
-- 10. RAW_OLT

------------------ 1. RAW_CUSTOMER_FEEDBACK ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_CUSTOMER_FEEDBACK;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_CUSTOMER_FEEDBACK AS
SELECT
  *,
  -- convert nanoseconds (NUMBER) -> seconds -> TIMESTAMP_NTZ
  TO_TIMESTAMP_NTZ(JOIN_DATE / 1000000000)       AS JOIN_DATE_CONVERTED,
  TO_TIMESTAMP_NTZ(ACTIVE_DATE / 1000000000)     AS ACTIVE_DATE_CONVERTED,
  TO_TIMESTAMP_NTZ(LAST_ONLINE_TS / 1000000000)  AS LAST_ONLINE_TS_CONVERTED,
  TO_TIMESTAMP_NTZ(LAST_OFFLINE_TS / 1000000000) AS LAST_OFFLINE_TS_CONVERTED
FROM HACKATHON.RAW.RAW_CUSTOMER_FEEDBACK;

------------------ 2. RAW_INCIDENT_TREND_SUMMARY ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_INCIDENT_TREND_SUMMARY;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_INCIDENT_TREND_SUMMARY AS
SELECT
  *,
  -- convert nanoseconds (NUMBER) -> seconds -> TIMESTAMP_NTZ
  TO_TIMESTAMP_NTZ(DATE / 1000000000)       AS DATE_CONVERTED
FROM HACKATHON.RAW.RAW_INCIDENT_TREND_SUMMARY;

------------------ 3. RAW_ML_FEATURES ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_ML_FEATURES;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_ML_FEATURES AS
SELECT
  *,
  -- convert nanoseconds (NUMBER) -> seconds -> TIMESTAMP_NTZ
  TO_TIMESTAMP_NTZ(TIMESTAMP_1H / 1000000000)       AS TIMESTAMP_1H_CONVERTED
FROM HACKATHON.RAW.RAW_ML_FEATURES;

------------------ 4. RAW_NETWORK_CONTEXT_STATIC ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_NETWORK_CONTEXT_STATIC;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_NETWORK_CONTEXT_STATIC AS
SELECT
  *
FROM HACKATHON.RAW.RAW_NETWORK_CONTEXT_STATIC;

------------------ 5. RAW_ONT_STATUS ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_ONT_STATUS;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_ONT_STATUS AS
SELECT
  *,
  -- convert nanoseconds (NUMBER) -> seconds -> TIMESTAMP_NTZ
  TO_TIMESTAMP_NTZ(DATE / 1000000000)             AS DATE_CONVERTED,
  TO_TIMESTAMP_NTZ(TIMESTAMP_1H / 1000000000)     AS TIMESTAMP_1H_CONVERTED
FROM HACKATHON.RAW.RAW_ONT_STATUS;

------------------ 6. RAW_TICKET_SUMMARY ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_TICKET_SUMMARY;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_TICKET_SUMMARY AS
SELECT
  *,
  -- convert nanoseconds (NUMBER) -> seconds -> TIMESTAMP_NTZ
  TO_TIMESTAMP_NTZ(DATE / 1000000000)       AS DATE_CONVERTED
FROM HACKATHON.RAW.RAW_TICKET_SUMMARY;

------------------ 7. RAW_EVENT_TRANSCRIPTS ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_EVENT_TRANSCRIPTS;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_EVENT_TRANSCRIPTS AS
SELECT
  *,
  -- convert nanoseconds (NUMBER) -> seconds -> TIMESTAMP_NTZ
  TO_TIMESTAMP_NTZ(TIMESTAMP_1H / 1000000000)       AS TIMESTAMP_1H_CONVERTED
FROM HACKATHON.RAW.RAW_EVENT_TRANSCRIPTS;

------------------ 8. RAW_CITY ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_CITY;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_CITY AS
SELECT
  *
FROM HACKATHON.RAW.RAW_CITY;

------------------ 9. RAW_CLUSTER ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_CLUSTER;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_CLUSTER AS
SELECT
  *
FROM HACKATHON.RAW.RAW_CLUSTER;

------------------ 10. RAW_OLT ------------------
DROP TABLE IF EXISTS HACKATHON.STAGING.STG_OLT;

CREATE OR REPLACE TABLE HACKATHON.STAGING.STG_OLT AS
SELECT
  *
FROM HACKATHON.RAW.RAW_OLT;