USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

SET CURRENT_USER = (SELECT CURRENT_USER());   
GRANT ROLE SNOWFLAKE_INTELLIGENCE_ADMIN TO USER IDENTIFIER($CURRENT_USER);
ALTER USER SET DEFAULT_ROLE = SNOWFLAKE_INTELLIGENCE_ADMIN;
ALTER USER SET DEFAULT_WAREHOUSE = SI_WH;

USE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
CREATE OR REPLACE WAREHOUSE SI_WH WITH WAREHOUSE_SIZE='large';
--------------------------------------------------
USE ROLE ACCOUNTADMIN;
-- Warehouse permission (required for Cortex indexing)
GRANT USAGE, OPERATE ON WAREHOUSE SI_WH 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

-- Full access to the database and everything under it
GRANT ALL PRIVILEGES ON DATABASE HACKATHON 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT ALL PRIVILEGES ON SCHEMA HACKATHON.DATAMART
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

GRANT SELECT ON VIEW HACKATHON.DATAMART.FACT_EVENT_TRANSCRIPTS 
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

-- CORTEX SEARCH SERVICE PERMISSION
GRANT CREATE CORTEX SEARCH SERVICE 
  ON SCHEMA HACKATHON.DATAMART
  TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

SHOW GRANTS TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
--------------------------------------------------
USE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

CREATE SCHEMA IF NOT EXISTS HACKATHON.AGENTS;
GRANT CREATE AGENT ON SCHEMA HACKATHON.AGENTS TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;

USE DATABASE HACKATHON;
USE SCHEMA DATAMART;
USE WAREHOUSE SI_WH;
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STAGE SEMANTIC_MODELS ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = ( ENABLE = TRUE );

CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_INTEGRATION
  TYPE=EMAIL
  ENABLED=TRUE
  DEFAULT_SUBJECT = 'SNOWFLAKE INTELLIGENCE';

create or replace procedure send_email(
    recipient_email varchar,
    subject varchar,
    body varchar
)
returns varchar
language python
runtime_version = '3.12'
packages = ('snowflake-snowpark-python')
handler = 'send_email'
as
$$
def send_email(session, recipient_email, subject, body):
    try:
        # Escape single quotes in the body
        escaped_body = body.replace("'", "''")
        
        # Execute the system procedure call
        session.sql(f"""
            CALL SYSTEM$SEND_EMAIL(
                'email_integration',
                '{recipient_email}',
                '{subject}',
                '{escaped_body}',
                'text/html'
            )
        """).collect()
        
        return "Email sent successfully"
    except Exception as e:
        return f"Error sending email: {str(e)}"
$$;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';