-- Create a service user for the connector
CREATE USER KAFKA_CONNECTOR_USER
  PASSWORD = 'TEMP_PASSWORD_123'
  DEFAULT_ROLE = KAFKA_CONNECTOR_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH;

-- Assign the public key
ALTER USER KAFKA_CONNECTOR_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApK61e+MBguRNXABBOG9PCFAn3iI2BmG5hu6qYZBc3oV/2TvCl1FwCP6ZYTGkRPOnsV/jVZKM5oqkLssJTrICft8PzxSSDNcyY0V8lFPpaLMu1zlQQrPwEs5+mSwBHC++8eWG8w8NdDIafbQkQojsGDjGqJiP1Tku0eSH0pchCWZAk79UdFapv/9HWsha0sF6efM+IAQFkzybDGG3Hv7ZrjTMdjYbbqSahRKqvb83HUekFd9xbE6MOcoCB1ppVRkSZp11lXfidF4mHczCvORauzE+6+6RBppToNqU9IsU3MH5dc8XxbFzTNYE1DfeI87/9Bm0LZDCtAE1giVtbwXI7QIDAQAB';

-- Verify it's set
DESC USER KAFKA_CONNECTOR_USER;

-- Create role for the connector
CREATE ROLE KAFKA_CONNECTOR_ROLE;

-- Grant permissions to write to your database/table
GRANT USAGE ON DATABASE HACKATHON TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON SCHEMA HACKATHON.RAW TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KAFKA_CONNECTOR_ROLE;

-- Assign role to user
GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER KAFKA_CONNECTOR_USER;

-- Grant permissions to write to the database/table
GRANT USAGE ON DATABASE HACKATHON TO ROLE KAFKA_CONNECTOR_ROLE;

-- Drop the old table
-- DROP TABLE HACKATHON.RAW.KAFKA_RAW_ML_FEATURES;

-- Create a new table with the correct schema for Snowpipe Streaming
CREATE TABLE HACKATHON.RAW.KAFKA_RAW_ML_FEATURES (
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT
);

GRANT USAGE ON SCHEMA HACKATHON.RAW TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT INSERT ON TABLE HACKATHON.RAW.KAFKA_RAW_ML_FEATURES TO ROLE KAFKA_CONNECTOR_ROLE;

-- CRITICAL: Allow creating internal stages for Snowpipe Streaming
GRANT CREATE STAGE ON SCHEMA HACKATHON.RAW TO ROLE KAFKA_CONNECTOR_ROLE;

-- Also need SELECT to verify data
GRANT SELECT ON TABLE HACKATHON.RAW.KAFKA_RAW_ML_FEATURES TO ROLE KAFKA_CONNECTOR_ROLE;

-- Verify all permissions
SHOW GRANTS TO ROLE KAFKA_CONNECTOR_ROLE;


--- Check the table
SELECT * FROM HACKATHON.RAW.KAFKA_RAW_ML_FEATURES;


-- Truncate the table
-- TRUNCATE TABLE HACKATHON.RAW.KAFKA_RAW_ML_FEATURES;