-- 1.  STG_CUSTOMER_FEEDBACK
-- 2.  STG_INCIDENT_TREND_SUMMARY
-- 3.  STG_ML_FEATURES
-- 4.  STG_NETWORK_CONTEXT_STATIC
-- 5.  STG_ONT_STATUS
-- 6.  STG_TICKET_SUMMARY
-- 7.  STG_EVENT_TRANSCRIPTS
-- 8.  STG_CITY
-- 9.  STG_CLUSTER
-- 10. STG_OLT

------------------ 1. STG_CUSTOMER_FEEDBACK ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_CUSTOMER_FEEDBACK AS
SELECT
  t.* EXCLUDE (
    JOIN_DATE, ACTIVE_DATE, LAST_ONLINE_TS, LAST_OFFLINE_TS,
    JOIN_DATE_CONVERTED, ACTIVE_DATE_CONVERTED, 
    LAST_ONLINE_TS_CONVERTED, LAST_OFFLINE_TS_CONVERTED
  ),
  t.JOIN_DATE_CONVERTED    AS JOIN_DATE,
  t.ACTIVE_DATE_CONVERTED  AS ACTIVE_DATE,
  t.LAST_ONLINE_TS_CONVERTED  AS LAST_ONLINE_TS,
  t.LAST_OFFLINE_TS_CONVERTED AS LAST_OFFLINE_TS
FROM HACKATHON.STAGING.STG_CUSTOMER_FEEDBACK t;

------------------ 2. STG_INCIDENT_TREND_SUMMARY ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_INCIDENT_TREND_SUMMARY AS
SELECT
  t.* EXCLUDE (
    DATE, DATE_CONVERTED
    ),
  t.DATE_CONVERTED    AS DATE
FROM HACKATHON.STAGING.STG_INCIDENT_TREND_SUMMARY t;

------------------ 3. STG_ML_FEATURES ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_ML_FEATURES AS
SELECT
  t.* EXCLUDE (
    TIMESTAMP_1H, TIMESTAMP_1H_CONVERTED
    ),
  t.TIMESTAMP_1H_CONVERTED    AS TIMESTAMP_1H
FROM HACKATHON.STAGING.STG_ML_FEATURES t;

------------------ 4. STG_NETWORK_CONTEXT_STATIC ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_NETWORK_CONTEXT_STATIC AS
SELECT * 
FROM HACKATHON.STAGING.STG_NETWORK_CONTEXT_STATIC t;

------------------ 5. STG_ONT_STATUS ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_ONT_STATUS AS
SELECT
  t.* EXCLUDE (
    DATE, TIMESTAMP_1H, DATE_CONVERTED, TIMESTAMP_1H_CONVERTED
    ),
  t.DATE_CONVERTED    AS DATE, 
  t.TIMESTAMP_1H_CONVERTED    AS TIMESTAMP_1H
FROM HACKATHON.STAGING.STG_ONT_STATUS t;

------------------ 6. STG_TICKET_SUMMARY ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_TICKET_SUMMARY AS
SELECT
  t.* EXCLUDE (
    DATE, DATE_CONVERTED
    ),
  t.DATE_CONVERTED    AS DATE
FROM HACKATHON.STAGING.STG_TICKET_SUMMARY t;

------------------ 7. STG_EVENT_TRANSCRIPTS ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.FACT_EVENT_TRANSCRIPTS AS
SELECT
  t.* EXCLUDE (
    TIMESTAMP_1H, TIMESTAMP_1H_CONVERTED
    ),
  t.TIMESTAMP_1H_CONVERTED    AS TIMESTAMP_1H
FROM HACKATHON.STAGING.STG_EVENT_TRANSCRIPTS t;

------------------ 8. STG_CITY ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.DIM_CITY AS
SELECT *
FROM HACKATHON.STAGING.STG_CITY t;

------------------ 9. STG_CLUSTER ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.DIM_CLUSTER AS
SELECT *
FROM HACKATHON.STAGING.STG_CLUSTER t;

------------------ 10. STG_OLT ------------------
CREATE OR REPLACE VIEW HACKATHON.DATAMART.DIM_OLT AS
SELECT *
FROM HACKATHON.STAGING.STG_OLT t;