-- 11.  FACT_MERGED_TICKET_N_FEEDBACK
-- 12.  FACT_NETWORK_REALTIME_STATUS

------------------ 11. FACT_MERGED_TICKET_N_FEEDBACK ------------------
CREATE OR REPLACE TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK AS
SELECT
    -- keep all ticket columns and rename duplicates with _x
    t.customer_id,
    t.city          AS city_x,
    t.city_key      AS city_key_x,
    t.region        AS region_x,
    t.* EXCLUDE (customer_id, city, city_key, region),

    -- keep all feedback columns and rename duplicates with _y
    f.city          AS city_y,
    f.city_key      AS city_key_y,
    f.region        AS region_y,
    f.* EXCLUDE (customer_id, city, city_key, region)

FROM HACKATHON.STAGING.STG_TICKET_SUMMARY t
INNER JOIN HACKATHON.STAGING.STG_CUSTOMER_FEEDBACK f
    ON t.customer_id = f.customer_id;
-- verify city_x
SELECT
    city_x,
    COUNT(*) AS count
FROM HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
GROUP BY city_x
ORDER BY count DESC;
-- verify city_y
SELECT
    city_y,
    COUNT(*) AS count
FROM HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
GROUP BY city_y
ORDER BY count DESC;

-- drop the unused columns
ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
DROP COLUMN
    "ACTIVE_DATE",
    "DATE",
    "JOIN_DATE",
    "LAST_OFFLINE_TS",
    "LAST_ONLINE_TS",
    "FEEDBACK_ID",
    "FEEDBACK_TOPIC",
    "SENTIMENT_LABEL",
    "FEEDBACK_CHANNEL",
    "FEEDBACK_TEXT",
    "RATING_1_5";

ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
ADD COLUMN DATE DATE;

UPDATE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
SET DATE = CAST(DATE_CONVERTED AS DATE);

-- drop the unused columns
ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
DROP COLUMN
    "DATE_CONVERTED";

ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
RENAME COLUMN ACTIVE_DATE_CONVERTED TO "ACTIVE_DATE";

ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
RENAME COLUMN JOIN_DATE_CONVERTED TO "JOIN_DATE";

ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
RENAME COLUMN LAST_OFFLINE_TS_CONVERTED TO "LAST_OFFLINE_TS";

ALTER TABLE HACKATHON.DATAMART.FACT_MERGED_TICKET_N_FEEDBACK
RENAME COLUMN LAST_ONLINE_TS_CONVERTED TO "LAST_ONLINE_TS";

------------------ 12. FACT_NETWORK_REALTIME_STATUS ------------------
CREATE OR REPLACE TABLE HACKATHON.DATAMART.FACT_NETWORK_REALTIME_STATUS AS
SELECT
  t.* EXCLUDE (
    TIMESTAMP_1H, DATE, TIMESTAMP_1H_CONVERTED, DATE_CONVERTED,
    STRESS, PRECURSOR_FLAG
  ),
  t.TIMESTAMP_1H_CONVERTED    AS TIMESTAMP_1H,
  t.DATE_CONVERTED            AS DATE
FROM HACKATHON.STAGING.STG_ONT_STATUS t;

ALTER TABLE HACKATHON.DATAMART.FACT_NETWORK_REALTIME_STATUS
ADD COLUMN DATE_D DATE;

UPDATE HACKATHON.DATAMART.FACT_NETWORK_REALTIME_STATUS
SET DATE_D = CAST(DATE AS DATE);